import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, symlinkSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const tool=path.resolve(process.cwd(),'scripts/workspace-relocation.mjs');
function git(root:string,...args:string[]){return execFileSync('git',['-C',root,...args],{encoding:'utf8'}).trim();}
function fixture(missing=false){const outer=realpathSync(mkdtempSync(path.join(os.tmpdir(),'yylo relocation space ü-')));const root=path.join(outer,'controller');mkdirSync(path.join(root,'.juno_task/state'),{recursive:true});git(outer,'init','-q','--initial-branch=main',root);git(root,'config','user.email','fixture@example.invalid');git(root,'config','user.name','Fixture');writeFileSync(path.join(root,'README.md'),'fixture\n');git(root,'add','.');git(root,'commit','-qm','base');const head=git(root,'rev-parse','HEAD');const old=path.join(outer,'old machine','controller');const moved=path.join(outer,'new machine','controller');mkdirSync(moved,{recursive:true});const state={schema_version:'juno_task_workspace_state.v1',tasks:{ABC123:{task_id:'ABC123',state:'WORKING',repository:old,worktree:path.join(old,'worktrees','ABC123'),base_sha:head,tip_sha:missing?'f'.repeat(40):head,target_ref:'refs/heads/main'}}};writeFileSync(path.join(root,'.juno_task/state/tasks.json'),JSON.stringify(state,null,2)+'\n');git(root,'add','.');git(root,'commit','-qm','state');return {outer,root,old,moved};}
function run(root:string,args:string[]){return spawnSync(process.execPath,[tool,...args],{cwd:root,encoding:'utf8'});}
describe('receipt-bound workspace relocation',()=>{
 it('plans, applies, and verifies unrelated roots with spaces and Unicode',()=>{const f=fixture();const plan=path.join(f.outer,'plan.json');const receipt=path.join(f.outer,'receipt.json');let r=run(f.root,['plan','--controller',f.root,'--map',`${f.old}=${f.moved}`,'--output',plan]);expect(r.status,r.stderr).toBe(0);expect(JSON.parse(r.stdout).changes.length).toBe(2);r=run(f.root,['apply','--controller',f.root,'--plan',plan,'--receipt',receipt]);expect(r.status,r.stderr).toBe(0);expect(readFileSync(path.join(f.root,'.juno_task/state/tasks.json'),'utf8')).toContain(f.moved);r=run(f.root,['verify','--controller',f.root,'--receipt',receipt]);expect(r.status,r.stderr).toBe(0);expect(JSON.parse(r.stdout).outcome).toBe('verified');});
 it('fails closed for missing candidate objects without changing state',()=>{const f=fixture(true);const before=readFileSync(path.join(f.root,'.juno_task/state/tasks.json'));const plan=path.join(f.outer,'plan.json');const receipt=path.join(f.outer,'receipt.json');expect(run(f.root,['plan','--controller',f.root,'--map',`${f.old}=${f.moved}`,'--output',plan]).status).toBe(0);const r=run(f.root,['apply','--controller',f.root,'--plan',plan,'--receipt',receipt]);expect(r.status).toBe(2);expect(r.stderr).toContain('missing commit objects');expect(readFileSync(path.join(f.root,'.juno_task/state/tasks.json'))).toEqual(before);});
 it('rejects symlink roots and tampered or stale plans',()=>{const f=fixture();const alias=path.join(f.outer,'alias');symlinkSync(f.moved,alias,'dir');expect(run(f.root,['plan','--controller',f.root,'--map',`${f.old}=${alias}`,'--output',path.join(f.outer,'bad.json')]).stderr).toContain('non-symlink');const plan=path.join(f.outer,'plan.json');expect(run(f.root,['plan','--controller',f.root,'--map',`${f.old}=${f.moved}`,'--output',plan]).status).toBe(0);const value=JSON.parse(readFileSync(plan,'utf8'));value.changes[0].new_value+='tampered';writeFileSync(plan,JSON.stringify(value));expect(run(f.root,['apply','--controller',f.root,'--plan',plan,'--receipt',path.join(f.outer,'r.json')]).stderr).toContain('integrity mismatch');});
});

describe('active path portability scanner',()=>{
 it('reports no machine-specific path in shipped active surfaces',()=>{const scanner=path.resolve(process.cwd(),'scripts/check-path-portability.mjs');const result=spawnSync(process.execPath,[scanner,path.resolve(process.cwd(),'..')],{encoding:'utf8'});expect(result.status,result.stderr).toBe(0);expect(JSON.parse(result.stdout)).toMatchObject({findings:[],excluded_classes:expect.arrayContaining(['immutable receipts and runtime logs'])});});
});
